/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppExternal {
    }
}
declare global {
    interface HTMLAppExternalElement extends Components.AppExternal, HTMLStencilElement {
    }
    var HTMLAppExternalElement: {
        prototype: HTMLAppExternalElement;
        new (): HTMLAppExternalElement;
    };
    interface HTMLElementTagNameMap {
        "app-external": HTMLAppExternalElement;
    }
}
declare namespace LocalJSX {
    interface AppExternal {
    }
    interface IntrinsicElements {
        "app-external": AppExternal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-external": LocalJSX.AppExternal & JSXBase.HTMLAttributes<HTMLAppExternalElement>;
        }
    }
}
